"use client";

import { FormEvent, startTransition, useEffect, useState } from "react";
import { Check, Plus } from "lucide-react";

type Subject = { id: string; name: string };
type Chapter = { id: string; name: string; subjectId: string };
type Course = { id: string; title: string; subjectId: string };
type Sheet = { id: string; title: string; content: { summary?: string; keyIdeas?: string[] }; createdAt: string };
type Card = { id: string; question: string; answer: string; chapterId: string; nextReview: string };

export function LearningWorkspace({ mode }: { mode: "sheets" | "flashcards" }) {
  const [subjects, setSubjects] = useState<Subject[]>([]); const [chapters, setChapters] = useState<Chapter[]>([]); const [courses, setCourses] = useState<Course[]>([]); const [sheets, setSheets] = useState<Sheet[]>([]); const [cards, setCards] = useState<Card[]>([]); const [subjectId, setSubjectId] = useState(""); const [chapterId, setChapterId] = useState(""); const [courseId, setCourseId] = useState(""); const [feedback, setFeedback] = useState(""); const [revealed, setRevealed] = useState<string | null>(null);
  async function load() { const [subjectResponse, chapterResponse, courseResponse, sheetResponse, cardResponse] = await Promise.all([fetch("/api/subjects"), fetch("/api/chapters"), fetch("/api/courses"), fetch("/api/study-sheets"), fetch("/api/flashcards")]); if (subjectResponse.ok) setSubjects(await subjectResponse.json()); if (chapterResponse.ok) setChapters(await chapterResponse.json()); if (courseResponse.ok) setCourses(await courseResponse.json()); if (sheetResponse.ok) setSheets(await sheetResponse.json()); if (cardResponse.ok) setCards(await cardResponse.json()); }
  useEffect(() => { let cancelled = false; Promise.all([fetch("/api/subjects"), fetch("/api/chapters"), fetch("/api/courses"), fetch("/api/study-sheets"), fetch("/api/flashcards")]).then(async ([subjectResponse, chapterResponse, courseResponse, sheetResponse, cardResponse]) => { const subjectData = subjectResponse.ok ? await subjectResponse.json() : []; const chapterData = chapterResponse.ok ? await chapterResponse.json() : []; const courseData = courseResponse.ok ? await courseResponse.json() : []; const sheetData = sheetResponse.ok ? await sheetResponse.json() : []; const cardData = cardResponse.ok ? await cardResponse.json() : []; if (!cancelled) startTransition(() => { setSubjects(subjectData); setChapters(chapterData); setCourses(courseData); setSheets(sheetData); setCards(cardData); }); }).catch(() => { if (!cancelled) setFeedback("Connecte-toi pour utiliser cet espace."); }); return () => { cancelled = true; }; }, []);
  async function generateSheet(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/study-sheets", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ subjectId, chapterId: chapterId || undefined, courseIds: [courseId], title: "Fiche · " + (courses.find((course) => course.id === courseId)?.title ?? "Cours") }) }); setFeedback(response.ok ? "Fiche générée." : "Génération impossible."); if (response.ok) await load(); }
  async function reviewCard(id: string, quality: 1 | 2 | 3) { const response = await fetch(`/api/flashcards/${id}/review`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ quality }) }); if (response.ok) { setRevealed(null); await load(); } }
  return <div className="workspace-page"><div className="workspace-heading"><div><p className="eyebrow">PHASE 5 · APPRENTISSAGE</p><h1>{mode === "sheets" ? "Fiches de révision" : "Flashcards"}</h1><p className="muted">{mode === "sheets" ? "Transforme tes cours en synthèses exploitables." : "Révise avec une répétition espacée simple."}</p></div>{feedback && <span className="workspace-message">{feedback}</span>}</div>{mode === "sheets" ? <><form className="data-form wide-form" onSubmit={generateSheet}><h2 className="form-title">Nouvelle fiche</h2><div className="form-row"><label>Matière<select value={subjectId} onChange={(event) => setSubjectId(event.target.value)} required><option value="">Choisir</option>{subjects.map((subject) => <option key={subject.id} value={subject.id}>{subject.name}</option>)}</select></label><label>Chapitre<select value={chapterId} onChange={(event) => setChapterId(event.target.value)}><option value="">Aucun</option>{chapters.filter((chapter) => !subjectId || chapter.subjectId === subjectId).map((chapter) => <option key={chapter.id} value={chapter.id}>{chapter.name}</option>)}</select></label><label>Cours<select value={courseId} onChange={(event) => setCourseId(event.target.value)} required><option value="">Choisir</option>{courses.filter((course) => !subjectId || course.subjectId === subjectId).map((course) => <option key={course.id} value={course.id}>{course.title}</option>)}</select></label></div><button className="primary-button" type="submit"><Plus size={16} /> Générer la fiche</button></form><div className="learning-list">{sheets.map((sheet) => <article className="data-list" key={sheet.id}><div className="list-heading"><h2>{sheet.title}</h2><span>{new Date(sheet.createdAt).toLocaleDateString("fr-FR")}</span></div><p className="muted">{sheet.content.summary}</p>{sheet.content.keyIdeas?.slice(0, 4).map((idea) => <p className="learning-point" key={idea}>• {idea}</p>)}</article>)}</div></> : <section className="data-list"><div className="list-heading"><h2>À réviser maintenant</h2><span>{cards.length}</span></div>{cards.map((card) => <article className="flashcard" key={card.id}><button className="flashcard-question" onClick={() => setRevealed(revealed === card.id ? null : card.id)}>{card.question}</button>{revealed === card.id && <><p className="flashcard-answer">{card.answer}</p><div className="item-actions"><button className="skip-button" onClick={() => reviewCard(card.id, 1)}>Difficile</button><button className="skip-button" onClick={() => reviewCard(card.id, 2)}>Moyen</button><button className="complete-button" onClick={() => reviewCard(card.id, 3)}><Check size={14} /> Facile</button></div></>}</article>)}</section>}</div>;
}
